### ISSUE TITLE
Chrome not reachable 

### ISSUE THREAD

**Issue by remidi-ivy** [umihico/docker-selenium-lambda#12]
I'm unable to getting this error, when testing in local when running your latest code. Why is this happening? I have been trying to solve this for days. Is it typical for headless chrome version ?

```
[ERROR] WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=95.0.4638.0)
Stacktrace:
#0 0x004000a48463 <unknown>
#1 0x00400052050f <unknown>
#2 0x00400050f4c4 <unknown>
#3 0x00400050fea2 <unknown>
#4 0x004000511b12 <unknown>
#5 0x00400050a363 <unknown>
#6 0x004000521a72 <unknown>
#7 0x0040005860a9 <unknown>
#8 0x004000573683 <unknown>
#9 0x004000549b64 <unknown>
#10 0x00400054ab55 <unknown>
#11 0x004000a780fe <unknown>
#12 0x004000a8d9d0 <unknown>
#13 0x004000a79055 <unknown>
#14 0x004000a8ee18 <unknown>
#15 0x004000a6d82b <unknown>
#16 0x004000aa9f98 <unknown>
#17 0x004000aaa118 <unknown>
#18 0x004000ac559d <unknown>
#19 0x00400300640b <unknown>
```

**Comment by umihico** [comment]
Which environment did you get this error? On local or on actual lambda function? If local, could you tell me how did try?

**Comment by mangleddata** [comment]
Just wanted to comment, this worked for me (And this repo just simply works. Thank you @umihico !)
```
docker build -t ${IMAGE_NAME} . 
docker run -p 9000:8080 ${IMAGE_NAME}

```
On another terminal try below to validate

`curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
`

**Comment by umihico** [comment]
@mangleddata 
Thank you. I'll do the same on local 😄

@remidi-ivy 
I close this once but please feel free to reopen with detail.
