### ISSUE TITLE
Mismatched versions of Chromium and ChromeDriver

### ISSUE THREAD

**Issue by nermand** [umihico/docker-selenium-lambda#130]
The current version of the Chromium browser (v103) specified in the Dockerfile does not work with the specified Chromedriver (v106.0.5249.61).  

I would gladly make a pull request to update this, but I fail to make sense of the notion on https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/ 
Not sure which version would be 106

**Comment by Dormanator** [comment]
The 1036826 you see in the URL is actually the build number and not the version. That build number is for Chromium version 106.0.5249.119. 

There should be no mismatch between the driver and browser currently in the Dockerfile. I used it today without issue.

**Comment by Dormanator** [comment]
> The current version of the Chromium browser (v103) specified in the Dockerfile does not work with the specified Chromedriver (v106.0.5249.61).
> 
> I would gladly make a pull request to update this, but I fail to make sense of the notion on https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/ Not sure which version would be 106

The 1036826 you see in the Dockerfile is the build number for the Chromium browser not the version. That build number is for Chromium version 106.0.5249.119 (latest).

There should be no mismatch with the driver and browser version. The Dockerfile works for me with no issue.

**Comment by umihico** [comment]
@Dormanator 
Thank you.

@nermand 
Since CI tests works fine, I don't think there is a problem. I'm closing this issue but I'd like to know the issue you have if you share detail.

**Comment by nermand** [comment]
@umihico That's so wierd. When I executed lambda with this Dockerfile I got the following errors:
```
This version of ChromeDriver only supports Chrome version 106
Current browser version is 103.0.5060.0 with binary path /opt/chrome/chrome
```
Sorry for the false alarm.  

@Dormanator Is there a way to associate the Chromium version with the build number? Seems like I am missing something obvious 😅

**Comment by umihico** [comment]
Interesting. Do you mean you get the error log in AWS Cloudwatch?

> Is there a way to associate the Chromium version with the build number?

I spend a lot of time but couldn't find. [My approach](https://github.com/umihico/docker-selenium-lambda/blob/circleci/.circleci/config.yml#L55-L60) is to try fetching one by one until I get the right build number... Maybe we need to ask one of chrome dev members.

**Comment by nermand** [comment]
>Do you mean you get the error log in AWS Cloudwatch?  

Yes, exactly.  
I rolled back to v103, and it was working again. Later, I bumped the versions to v105 and it's working fine. 🤷

**Comment by umihico** [comment]
I see. This is wired and I've never seen before. Maybe my script is wrong and created wrong Dockerfile? (but they are all tested...)

I don't believe but possibly Google storage sometimes delivers wrong?

Anyway, I'm glad you have no problems now
