### ISSUE TITLE
Encounter error [WhatsApp Work with Google Chrome 60+ only] when using your Docker Image

### ISSUE THREAD

**Issue by Ammar-Azman** [umihico/docker-selenium-lambda#131]
First of all, thank you for creating the image that manage to make Google worked on Lambda. 

I have a project where I need to access WhatsApp web using AWS Lambda. Hence I am using you Dockerfile as preference. The code is working well on opening the Google Chrome, but.. as it accessed to WhatsApp web, if showed this kind error where 

###  [WhatsApp Work with Google Chrome 60+ only]

I have read some forums and articles and most of the time they said that you need to have a stable and updated Chrome to access WhatsApp web. 

I saw your Dockerfile is using 

- chromium 106.0.5249.0
- chromedriver 106.0.5249.61
 
Is it possible that this version is not compatible to access WhatsApp web? Or can we just using Chrome, not Chromium? This because it most probably that WhatsApp not allowed their website running on Chromium.

If you don't mind, can I know what is your reference on the link that you used to download the chromium and chromedriver in the Dockerfile? ( which is this `"https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_linux64.zip"` and `https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1036826%2Fchrome-linux.zip?alt=media:`) 

Thank you.

**Comment by Ammar-Azman** [comment]
Can you help me?

**Comment by x-N0** [comment]
You can lookup for the latest stable Chrome driver and Chromium here:
https://omahaproxy.appspot.com/


Check the latest version for your OS, copy it to the version information lookup, and then use the branch base position to filter in the snapshots until you get the one closest to your number, you'll get a url like this:

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/1121454/

There you have the zip file of the realease.


For the chromedriver use this link and replace with ur release version:

`https://chromedriver.storage.googleapis.com/<release_version>/chromedriver_linux64.zip`
e.g.: https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip

Hope it helps, @Ammar-Azman !!
