### ISSUE TITLE
docker-selenium-lambda repository가 업데이트 될 때마다 ECR에 자동으로 이미지를 업로드 할 수 있습니까?

### ISSUE THREAD

**Issue by dlrjsgh367** [umihico/docker-selenium-lambda#167]
안녕하세요 umihico.

자동으로 최신버전의 image를 업로드할 수 있는 방법이 있습니까?.

귀하의 답변을 기다립니다.

**Comment by umihico** [comment]
@dlrjsgh367 

I fixed CI and latest docker image were uploaded just now. It should keep updating docker image from now.
#171
