### ISSUE TITLE
How to find the missing libraries for the driver binary?

### ISSUE THREAD

**Issue by QinyuanWu** [umihico/docker-selenium-lambda#184]
Thank you for publishing this repo, it is the only approach that currently works across the internet and is life saving. My question is:
1. How did you find the exact libraries that are missing for the chrome driver/browser? 
2. How did you find the chrome versions that the specific Selenium version is supporting? 

I want to know these in case I want to use a different chrome or Selenium version. Thanks!

**Comment by umihico** [comment]
@QinyuanWu 
Hello, as you can see my Github Action files, I could get all versions from [here](https://github.com/umihico/docker-selenium-lambda/blob/5dc9bf7ee7e0c470dad4c7ba23e79547903d2dc2/.github/workflows/auto-update.yml#L30C16-L30C16). 

But, after v115, it stopped updating. It seems I have to refer [this](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints). But I don't make workable CI yet.
