### ISSUE TITLE
Great showcase/demo, it worked seamlessly. Is there any reason this couldn't be rewritten in java?

### ISSUE THREAD

**Issue by samburt0n5** [umihico/docker-selenium-lambda#185]
So have the docker container setup similar but building a java app using gradle/maven using a jdk as runtime and have some java/kotlin code running a handler that contains some selinium code.

If you think that's feasible I would like to take your code and modify it slightly to do that.

Thanks in advance.

**Comment by umihico** [comment]
I don't see specific reasons, if selenium library exists as same as Python. You can refer my code as you want. Thank you.
