### ISSUE TITLE
Consider streamlining the chromedriver and chrome versions

### ISSUE THREAD

**Issue by filipopo** [umihico/docker-selenium-lambda#187]
Apparently chromedriver can cause a problem if it's not matching the exact same major version of chrome_linux64:
https://stackoverflow.com/questions/41133391/which-chromedriver-version-is-compatible-with-which-chrome-browser-version

chromedriver is currently version 114 and chrome-linux is now version 113?:
https://github.com/umihico/docker-selenium-lambda/blob/5dc9bf7ee7e0c470dad4c7ba23e79547903d2dc2/Dockerfile#L4C7-L4C7

**Comment by umihico** [comment]
They are both 114.

CI notes exact version info every releases like [this](https://github.com/umihico/docker-selenium-lambda/releases/tag/2023-07-14-015924).

But I have to make some change to adapt 115 or later tho.

https://chromedriver.chromium.org/downloads says  

> If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.
