### ISSUE TITLE
Error: Operation not permitted' during 'pthread_create

### ISSUE THREAD

**Issue by vagyvin** [umihico/docker-selenium-lambda#228]
When I used the Dockerfile from this repo and try to build I get an error 
`Sending build context to Docker daemon  5.632kB
Step 1/9 : FROM public.ecr.aws/lambda/python@sha256:1d922f123370801843aad18d0911759c55402af4d0dddb601181df4ed42b2ce2 as build
 ---> 50ead346a5f9
Step 2/9 : RUN dnf install -y unzip &&     curl -Lo "/tmp/chromedriver-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/linux64/chromedriver-linux64.zip" &&     curl -Lo "/tmp/chrome-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/linux64/chrome-linux64.zip" &&     unzip /tmp/chromedriver-linux64.zip -d /opt/ &&     unzip /tmp/chrome-linux64.zip -d /opt/
 ---> Running in 323d53d6f5ca

(dnf:7): GLib-ERROR **: 16:15:15.890: file ../glib/gthread-posix.c: line 1340 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
The command '/bin/sh -c dnf install -y unzip &&     curl -Lo "/tmp/chromedriver-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/linux64/chromedriver-linux64.zip" &&     curl -Lo "/tmp/chrome-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.58/linux64/chrome-linux64.zip" &&     unzip /tmp/chromedriver-linux64.zip -d /opt/ &&     unzip /tmp/chrome-linux64.zip -d /opt/' returned a non-zero code: 133`

**Comment by umihico** [comment]
I am not sure this is my repository's problem. Can your environment build like below?

```
FROM amazonlinux:2023
RUN dnf upgrade -y
```

**Comment by vagyvin** [comment]
I updated my Dockerfile to this instead. Works now.
`FROM umihico/aws-lambda-selenium-python:latest
RUN pip install selenium
RUN pip install bs4
COPY main.py ./
CMD [ "main.handler" ]`

**Comment by umihico** [comment]
Thank you for your updates. I'll consider applying your patch if this issue collect lots of impressions 👍
