### ISSUE TITLE
Python with Alpine Linux to make the image size smaller?

### ISSUE THREAD

**Issue by vagyvin** [umihico/docker-selenium-lambda#231]
Is it possible to use Alpine linux to make the image size smaller?

**Comment by umihico** [comment]
Hello @vagyvin,

In theory, it is possible. However, this would require some dependencies like aws-lambda-ric, and maybe more.

I want to make my Dockerfile as small as possible for an example. So given these considerations, I'm currently not planning to switch to Alpine Linux.
