### ISSUE TITLE
SessionNotCreatedException running container in aws Lambda

### ISSUE THREAD

**Issue by jddreher** [umihico/docker-selenium-lambda#258]
I am pretty new to running python via container in AWS Lambda so this may be a configuration issue but running this container directly, no modification throws this error. Do you have any ideas as to what is causing it?
Dockerfile is the example in this repo, main.py is also the same. No overrides in place.

{
  "errorMessage": "Message: session not created: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location /opt/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x56333a109c7a <unknown>\n#1 0x563339dece2c <unknown>\n#2 0x563339e21d6a <unknown>\n#3 0x563339e1e17b <unknown>\n#4 0x563339e68c49 <unknown>\n#5 0x563339e5c363 <unknown>\n#6 0x563339e2c247 <unknown>\n#7 0x563339e2cb9e <unknown>\n#8 0x56333a0d024b <unknown>\n#9 0x56333a0d42f1 <unknown>\n#10 0x56333a0bbafe <unknown>\n#11 0x56333a0d4e52 <unknown>\n#12 0x56333a0a079f <unknown>\n#13 0x56333a0f9638 <unknown>\n#14 0x56333a0f9810 <unknown>\n#15 0x56333a108dac <unknown>\n#16 0x7fddc514f7f2 start_thread\n",
  "errorType": "SessionNotCreatedException",
  "requestId": "926f1a5e-9408-4469-a008-a9971739786f",
  "stackTrace": [
    "  File \"/var/task/main.py\", line 24, in handler\n    chrome = webdriver.Chrome(options=options, service=service)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"
  ]
}

**Comment by umihico** [comment]
@jddreher 

> running this container directly

I couldn't understand this exactly how but I guess you didn't use Serverless Framework? I suggest to deploy with Serverleff Framework once as README says, then you can compare the configuration diffs between these two?
