### ISSUE TITLE
Changes needed to support Mac M1 processors

### ISSUE THREAD

**Issue by greattypo** [umihico/docker-selenium-lambda#27]
Thank you so much for sharing this repo, I have found it immensely helpful! Unfortunately, I recently switched to an M1 Mac and the instructions no longer work. Here is what I have figured out (I think):

- M1 Macs requires adding `"architecture: arm64"` in serverless.yml. Otherwise you will get a `"Runtime.InvalidEntrypoint"` error.
- M1 Macs requires choosing a region that supports Lambda arm64 (i.e. `us-east-1` works, `us-west-1` does not)
- M1 Macs require a special ARM version of Chromedriver, otherwise you will get an "`OSError: [Errno 8] Exec format error.`" I haven't been able to figure this one out. There is an ARM version here but it seems to be for Ubuntu/Debian (https://ubuntu.pkgs.org/18.04/ubuntu-updates-universe-arm64/chromium-chromedriver_95.0.4638.69-0ubuntu0.18.04.1_arm64.deb.html)
- M1 Macs _can_ build docker images under AMDx64, but the command require does not seem to be supported by `sls deploy`.

Anyway I really wish I could help more, but that's about the limits of my ability. If you have any suggestions for how to make this work I'd be very grateful!

**Comment by umihico** [comment]
@greattypo 
Thank you for reporting! The same thing happened exactly in my new M1 Mac too. (I also recently changed to M1 but didn't try this repo 
 yet, sorry.)

Deployment goes fine, but invoking got the error below:

```
{
    "errorMessage": "RequestId: ed83ea06-69d2-11ec-90d6-0242ac120003 Error: fork/exec /lambda-entrypoint.sh: exec format error",
    "errorType": "Runtime.InvalidEntrypoint"
}

 Serverless Error ----------------------------------------

  Invoked function failed

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              17.2.0
     Framework Version:         2.68.0
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

After I added `platform: linux/amd64` on #28 , my lambda function works fine even if deployed by M1 Mac. I hope it helps you too.

**Comment by greattypo** [comment]
That worked! Thank you so much for the speedy fix 🙏
