### ISSUE TITLE
Can't run the latest chrome properly in AWS Lambda

### ISSUE THREAD

**Issue by umihico** [umihico/docker-selenium-lambda#3]
I was facing unknown errors and try using google-chrome directly without selenium and chromedriver.

when I execute this command in my local image, this prints HTML fine, but print empty string when I execute in Lambda function.

`google-chrome --user-data-dir=/tmp/home/user-data --no-sandbox --headless --disable-gpu --dump-dom https://example.com`

[7831d4d](https://github.com/umihico/docker-selenium-lambda/commit/7831d4d3a30028d0a741f59e5ef1dd3461ad317b)

**Comment by umihico** [comment]
Chrome probably tries to write cert files below and fails because only `/tmp` is writable.

`/home/sbx_user1051/.pki/nssdb/cert9.db`
`/home/sbx_user1051/.pki/nssdb/pkcs11.txt`
`/home/sbx_user1051/.pki/nssdb/key4.db`

I don't get how to change this path.

**Comment by umihico** [comment]
Not related. In local machine chrome still print dom properly regardless I lock the entire directory by `RUN chmod 700 /home`, local also fail to write files

**Comment by umihico** [comment]
When I added args `--single-process` and `--disable-dev-shm-usage` on 95e8b20, I noticed google-chrome does visit the website by checking website access, but then the chrome process hangs until the lambda function's timeout. 

I don't know why --single-process matters but `--disable-dev-shm-usage` works probably `/dev/shm` is not writable in AWS Lambda. This option use `/tmp` instead of `/dev/shm`

**Comment by lifesaverluke** [comment]
In case you want to try a newer Chromium version: I regularly compile new versions and make them available at www.chromiumforlamda.com

**Comment by umihico** [comment]
@lifesaverluke 
Thank you, but your link looks like broken now, and [this official repository](https://github.com/aws-samples/serverless-ui-testing-using-selenium) gave me a possible solution and I'd try soon.

**Comment by umihico** [comment]
fixed by https://github.com/umihico/docker-selenium-lambda/pull/10 🎉
