### ISSUE TITLE
I have a confusion related to Dockerfile

### ISSUE THREAD

**Issue by faizanalhassan** [umihico/docker-selenium-lambda#35]
Hi Umihico,
Thanks for this wonderful project. 
Actually, I am not that experienced with docker, but what I have learned, the `FROM` clause ending with `as <something>` is used to pull it temporarily and then only use it for some build steps.
But what looks to me is, your both `FROM` clause is referring the same image. So can you explain the reason why you first pulled it as a builder and then as a base image?

**Comment by umihico** [comment]
Let me specify a commit for other readers. We are talking about [this Dockerfile](https://github.com/umihico/docker-selenium-lambda/blob/de29feac9d5cd9ff490d0e782734d15bc0134a7d/Dockerfile)

There are some benefits. First, as you can see in the `build` stage, I had to install `unzip` and got heavy zip files. If I keep going with this image, we have to upload these unnecessary stuff together, but you know we just want binaries.

Second, separating stages can improve cache efficiency while local development. We can keep cache of yum's and pip's even if url changes.

**Comment by umihico** [comment]
In `build` stage, I don't have to use same lambda image to download binaries, but I use exactly same image to skip extra pulling image

**Comment by faizanalhassan** [comment]
Got it. Thanks.
