### ISSUE TITLE
I am just using serverless first time for a project. Can you check I am doing it right?

### ISSUE THREAD

**Issue by faizanalhassan** [umihico/docker-selenium-lambda#36]
Hi Umihiko,
I have updated the `serverless.yml` file from your repo and also a little updated the `Dockerfile` ([both files can be viewed here](https://gist.github.com/faizanalhassan/36da894be0563af29b14f17c6ac65dd9)). This is tree structure of my directory:
![image](https://user-images.githubusercontent.com/53539447/148692948-5ccd73d5-d85d-4ea0-a9ab-647ab15db318.png)

Both lambdas are deployed and working. And I will add more scrapers in a similar pattern.
Do you think my Dockerfile and serverless.yml are okay? or else if you can suggest necessary updates?

Also:
- Is the s3 bucket, serverless creates, is usable in my case? 
 And is there a way to tell serverless not to create the bucket?
- Each time I run `sls deploy`, it recreates all images.
 How should I tell it to not recreate images for scrapers which have no updates?
- Its image details and function details are written in separate sections (as you see in the `serverless.yml` file I attached).
 How to tell it to only deploy function (e.g.) `china_post` and not the `aramex` (bcz it was deployed in the previous run)?
 or will mentioning the function name (by using some argument at deploy time) will stop serverless to recreating the image for `china_post`? because the image details are written separately under `ecr` section.
- Each time I deploy, instead of overwriting the previous images, it creates new ones and removes the tag from the previous ones. I want to make sure, I get only one image for each scraper. if you know how to do that?

**Comment by umihico** [comment]
You can use shared one image and just need to change `command`.

```yml
functions:
  func1:
    image:
      name: latest
      command: "aramex.handler" # here
  func2:
    image:
      name: latest
      command: "china_post.handler" # here
```

You can use `cacheFrom` to decrease building time probably.

I recommend to read basic documents first.
https://www.serverless.com/framework/docs/providers/aws/guide/functions
https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy-function
