### ISSUE TITLE
How can I locally test my serverless functions during development?

### ISSUE THREAD

**Issue by Hoffmano** [umihico/docker-selenium-lambda#44]
What method do you use to develop serverless docker functions if `sls offline` can't run docker images?

**Comment by umihico** [comment]
I don't use `sls offline` and not familiar with it, sorry.

Are you using M1 Mac? I figured out that docker builds things fine but running chromium seems impossible inside of this image with M1 mac. I need more time to be sure about this.

If you are not M1 user, this way must work for you
https://github.com/umihico/docker-selenium-lambda/issues/12#issuecomment-988425287

If you want execute your code in actual AWS Lambda with frequent modification, this my repository may help you. This sends your code without deploying.
https://github.com/umihico/pythonista-chromeless

I am not sure my answers helped you enough and I am happy to help you if there is detail.

**Comment by Hoffmano** [comment]
Very good @umihico 
The solution proposed [here](https://github.com/umihico/docker-selenium-lambda/issues/12#issuecomment-988425287) works fine

But now raised a new "problem"

In my case I have a container with multiple functions
```
--- app.js
def google(event=None, context=None):
  driver = webdriver.Chrome("/opt/chromedriver", options=options)
  driver.get("https://google.com")
  title = driver.title
  driver.close()
  driver.quit()

  return title

def handler(event=None, context=None):
  driver = webdriver.Chrome("/opt/chromedriver", options=options)
  driver.get("https://editorconfig.org/")
  title = driver.title
  driver.close()
  driver.quit()

  return title

--- serverless.yml

functions:
  handler:
    image:
      name: image
      command:
        - app.handler

  google:
    image:
      name: image
      command:
        - app.google
```

But I doesn't know how to invoke that functions

Every time that I invoke a function by `http://localhost:8080/2015-03-31/functions/function/invocations` is executed only handler.  Do you know how can I specify to invoke google function?

**Comment by umihico** [comment]
How about this? If you add this code below at the end of file, you can `docker build . -t selenium && docker run --rm -it --entrypoint '' selenium python test.py`

```python
if __name__ == '__main__':
    handler() # or google()
```
