### ISSUE TITLE
/tmp size

### ISSUE THREAD

**Issue by Gianfranco-gb** [umihico/docker-selenium-lambda#56]
Hello,
I used this Dockerfile to use it as webscrapping and saving the data in /tmp folder of lambda.
The problem I get is that the disk of the "/tmp/" folder gets bigger and bigger and reaches the limit of 514 MB of space.
I listed all the files and directories inside this folder to see what is the problem, and I get that the total of the size is less than the 514 MB, the biggest one is 345KB.
So the remaining is not located anywhere inside the "tmp" folder. So I don't understand why it says I reach the limit when the total of the sum doesn't reach even the 500 MB, as I said the biggest one was 345KB.

I would like to know if for you happens the same? 

Thanks.

**Comment by umihico** [comment]
I guess it is probably chrome generate temp files under `/tmp`. My script configures them by `mkdtemp` function, but I have no idea if you say they seems invisible and you can't list any.

Maybe as you know, you can avoid this issue by using S3 or mounted EFS storage.

As you see _Temporary storage with /tmp_ in [here](https://aws.amazon.com/jp/blogs/compute/choosing-between-aws-lambda-data-storage-options-in-web-apps/), some data under /tmp still stays there between invocations, but again, they should be visible.

**Comment by Gianfranco-gb** [comment]
Thanks,
I have noticed that in this /tmp folder every time I execute my function it creates some files named "core.chrome.X"
X --> A random number
And these files are the problem, because some of them have the size of 255MB and others 145KB.

But this only happens when I use the function that creates temporary directories, when I don't use it, these file doesn't even reach de 1 MB any of them.

This make sense to you?
Is it created by selenium or something? 
Do you have any idea what are those files? 

Thanks for your time and your knowledge.

**Comment by umihico** [comment]
They are generated by chrome and we don't have valid options about this as far as I know. Also I don't know well their file creation behaviors.
If you dig into what we can do with chrome options, you might find some ideas. (no guarantees)

**Comment by umihico** [comment]
@Gianfranco-gb 
Wow found a great latest news ;)
https://aws.amazon.com/jp/about-aws/whats-new/2022/03/aws-lambda-configure-ephemeral-storage/
