### ISSUE TITLE
docker-selenium-firefox-lambda

### ISSUE THREAD

**Issue by MauroLondon** [umihico/docker-selenium-lambda#61]
Hello, I really appreciate the time you take to share this great solution. Now, you have something similar but with firefox?

**Comment by umihico** [comment]
Thank you for your comment. I haven't tried yet, but I think it is possible.

I found this AWS official repository and this shaped most of my current Dockerfile. As you see they also test with Firefox too, you can do it.

https://github.com/aws-samples/serverless-ui-testing-using-selenium

**Comment by MauroLondon** [comment]
Your code is fantastic, it was very useful for a website, however for
another website it was impossible for me to use it since the web response
was an internal error. So, I saw that locally it runs without problems,
including the chromium binary and the webdriver. However with your code in
the lambda it doesn't get executed. So I found this other code:
https://stackoverflow.com/questions/65429877/aws-lambda-container-running-selenium-with-headless-chrome-works-locally-but-not/66594707#66594707
:

# 1) DOWNLOAD BASE IMAGE.
FROM public.ecr.aws/ubuntu/ubuntu:18.04_edge# 2) DEFINE GLOBAL ARGS.
ARG MAIN_FILE="main.py"
ARG ENV_FILE="params.env"
ARG REQUIREMENTS_FILE="requirements.txt"
ARG FUNCTION_ROOT="."
ARG RUNTIME_VERSION="3.8"
ARG LAMBDA_TASK_ROOT="/var/task"
ARG LAMBDA_RUNTIME_DIR="/var/runtime"
ENV LAMBDA_TASK_ROOT="/var/task"
ENV LAMBDA_RUNTIME_DIR="/var/runtime"# 3) CREATE FUNCTION DIR
WORKDIR ${LAMBDA_TASK_ROOT}# 4) COPY FILES.# Copy The Main .py File.
COPY ${MAIN_FILE} ${LAMBDA_TASK_ROOT}# Copy The .env File.
COPY ${ENV_FILE} ${LAMBDA_TASK_ROOT}# Copy The requirements.txt File.
COPY ${REQUIREMENTS_FILE} ${LAMBDA_TASK_ROOT}# Copy Helpers Folder.
COPY helpers/ ${LAMBDA_TASK_ROOT}/helpers/# Copy Private Folder.
COPY priv/ ${LAMBDA_TASK_ROOT}/priv/# Copy Source Data Folder.
COPY source_data/ ${LAMBDA_TASK_ROOT}/source_data/# 5) DOWNLOAD &
INSTALL CHROMEIUM + CHROMEDRIVER.
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y wget \
  unzip \
  libx11-dev \
  nano \
  g++ \
  make \
  cmake \
  unzip \
  python3.7 \
  python3-pip \
  libcurl4-openssl-dev \
  libfontconfig \
  xvfb \
  libnss3-dev \
  libosmesa6-dev \
  ffmpeg# 6) CREATE LINKS
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN ln -s /usr/bin/python3.7 /usr/bin/python
RUN ln -s /usr/lib/x86_64-linux-gnu/libOSMesa.so
/usr/local/bin/libosmesa.so# 7) INSTALL DEPENDENCIES.
RUN python -m pip install --upgrade pip
RUN python -m pip install wheel
RUN python -m pip install urllib3
RUN python -m pip install awslambdaric
RUN python -m pip install -r requirements.txt --default-timeout=100#
8) INSTALL CHROME
RUN wget https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-37/stable-headless-chromium-amazonlinux-2017-03.zip
RUN unzip ./stable-headless-chromium-amazonlinux-2017-03.zip
RUN rm ./stable-headless-chromium-amazonlinux-2017-03.zip
RUN mv -f ./headless-chromium /usr/local/bin/headless-chromium
RUN chmod 755 /usr/local/bin/headless-chromium# 9) INSTALL CHROMEDRIVER
RUN wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
RUN unzip ./chromedriver_linux64.zip
RUN rm ./chromedriver_linux64.zip
RUN mv -f ./chromedriver /usr/local/bin/chromedriver
RUN chmod 755 /usr/local/bin/chromedriver# 10) DEFINE ENV VARS
ENV AWS_LAMBDA_RUNTIME_API=""
ENV DISPLAY=":20"# 11) SET CMD OF HANDLER.
ENTRYPOINT [ "/usr/bin/python", "-m", "awslambdaric" ]
CMD [ "main.lambda_handler" ]


 which is I execute with the expected response, but it takes more than 10
minutes, when on my local pc it only takes less than 30 seconds. I need it
to take no more than 30 seconds since I am integrating the lambda to an AWS
API gateway. Apparently using an ubuntu image solves my problem. The
public.ecr.aws/lambda/python image doesn't seem to work for me. Do you have
any idea why the above code takes so long? Is there any way to merge that
code with yours?

**Comment by umihico** [comment]
Please provide the actual entire log or detect which line(action) get stuck by logging.

I’d like to see there is a change if you increase memory.

The code is using adieuadieu’s binary which is really really old customized chromium. I think merging is difficult, especially when without knowing issue.

**Comment by MauroLondon** [comment]
Correct, I'm using adieuadieu's chrome driver. I have an idea that could be
the reason for the delay. I'll try to use newer drivers. My python code
doesn't have any delay elements to account for that delay. Indeed I have
the memory to the allowed limit (10240). It is a 5 step automation and each
step requires a web request and each request takes more than 2 minutes to
return the request response. That makes no sense.

I love your code, too bad I can't get it to work for the website I'm
automating. That's why I'm using the ubuntu image since it resembles the
environment I have on my pc where it works perfectly and returns the
response in less than 30 seconds.

I'll try testing with the latest chromo driver and keep you posted on my
progress.

**Comment by MauroLondon** [comment]
I can't figure out why the lambda function takes so long to respond to web
requests. I am using selenium with a chrome and I don't have any retarder
elements in the code. It looks like the lambda is blocking for periods of
time. So my question is, are there any limitations on the part of the
ECS-ECR service?

**Comment by umihico** [comment]
Could you provide cloudwatch log?

**Comment by MauroLondon** [comment]
[image: image.png]

REPORT RequestId: f89b655f-ed4a-4d2d-84db-20d8c285c029 Duration: 481084.94
ms Billed Duration: 483275 ms Memory Size: 10240 MB Max Memory Used: 282 MB
Init Duration: 2189.42 ms

Look at the execution sequence, as sometimes it delays for no reason, when
it is supposed to return a satisfactory response in no more than 25
seconds, just as it does when I run it on my PC

**Comment by umihico** [comment]
Thank you. You can insert `print` in every line with timestamp or another way as debugger, then you can detect which line is taking such long time.

**Comment by MauroLondon** [comment]
I already did, the delay is just when clicking the button to go to the next
flow. When clicked, it moves to a next form page....

Using your code, it runs super fast but the final request to click the
"submit app" button doesn't get executed as the web shows an internal error
in submitting the app. So I tried with Luke Halley's dockerfile and if it
manages to run to the end but it takes almost 10 minutes, which I can't
find a logical application for....

**Comment by umihico** [comment]
> I already did, the delay is just when clicking the button to go to the next
flow. When clicked, it moves to a next form page....

Thank you. I have had no idea until now what your issue is.

>  I saw that locally it runs without problems,
including the chromium binary and the webdriver.

When you tried, did you execute your code through exact the same built Docker image?

**Comment by MauroLondon** [comment]
In my local, I don't use docker image as such, I just point to the chrome
webdriver and the chromium binary and ready I run a python script and it
works perfectly in less than 30 seconds. When I want to take it to an aws
lambda, it is that the problems arise.

I tried your code first, and it works until I get to the last flow that
sends the final form data. But the shipment fails since the web fails to
process the final request.

I then tried, with the other code that references in the dockerfile, a base
image: FROM public.ecr.aws/ubuntu/ubuntu:18.04_edge. That solution does
work for me, but it takes a long time and that's what I can't understand.

Now, what distinguishes the web that cannot make it work well with your
code? What factor in the lambda can influence the loading delay of a page
when clicking a "next" button?

**Comment by umihico** [comment]
Trying exact same Docker image in your local may give you new clues. Could you try?

And could you check how much it consume memory, CPU and network traffic when you just do the same thing with normal browser? Are they really almost zero as same as other website forms?

**Comment by umihico** [comment]
https://github.com/umihico/docker-selenium-lambda/issues/12

**Comment by MauroLondon** [comment]
It makes sense to test the docker image locally. I'll give it a
try....Thank you for spending time on me.
