### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by bklaus002** [umihico/docker-selenium-lambda#69]
Many thanks for putting this docker here on Gitlab. I am new to this and have followed your steps (in Ubuntu, installed all needed elements along the way) but at the last step ("sls deploy"), I am getting the following error message.

Deploying docker-selenium-lambda to stage prod (eu-central-1)

✖ Stack docker-selenium-lambda-prod failed to deploy (193s)
Environment: linux, node 16.15.0, framework 3.16.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Encountered error during executing: docker push
...
dial tcp 3.121.166.70:443: i/o timeout

I searched a lot on Google but could not find anything related. Do you have any idea what might be the issue for me?

**Comment by umihico** [comment]
@bklaus002 

Building and pushing docker image may costs some memory and time. I suggest you to increase docker memory limit config but I am not sure it works. I want you to try deploying in another environment.

And could you check some ECR repositories were created and they have uploaded images inside? My guess is a repository is created but no images there.

**Comment by boeschl** [comment]
Thanks for posting this, I have been looking for an alternative for scrapping some sites, generating an API to use the website information and now is working !!!!
As an improvement, I tried to separate the elements and construct as a LAMBDA layer the elements of Selenium and Chrome, so is easier to deploy or even change the code of the scrapping (if the website changes something), but failed miserably.
The deployment only copies the files on the directory and nothing else any support will be greatly appreciated


Here is the content of the serverless.yml
service: docker-selenium-lambda

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-2'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64
layers:
  selenium-lambda:
    path: ./

And the Dockerfile
FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55 as build
RUN yum install -y unzip && \
    curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip" && \
    curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F982481%2Fchrome-linux.zip?alt=media" && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/chrome-linux.zip -d /opt/

FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55
RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel -y
RUN pip install selenium
COPY --from=build /opt/chrome-linux /opt/chrome
COPY --from=build /opt/chromedriver /opt/

**Comment by bklaus002** [comment]
> increase docker memory limit config

Unfortunately, I am really new to this and would need some concrete steps to follow or links. My guess is that I have not set the needed permissions so that the image can be uploaded to the repository. I followed your suggestion and indeed the repository was created, but no image is inside. I will check the permissions.

**Comment by umihico** [comment]
@bklaus002 

Maybe you can get more logs and details which step is hanging and why by `sls deploy --verbose`

**Comment by bklaus002** [comment]
> @bklaus002
> 
> Maybe you can get more logs and details which step is hanging and why by `sls deploy --verbose`

Here is the full log from `sls deploy --verbose`, but I am not sure that helps to understand where the problem is. 

sls deploy --verbose
To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.16.0")


Deploying docker-selenium-lambda to stage prod (eu-central-1)

Packaging
Sending build context to Docker daemon   12.8kB
Step 1/9 : FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55 as build
 ---> ec11cea4dd41
Step 2/9 : RUN yum install -y unzip &&     curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip" &&     curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F982481%2Fchrome-linux.zip?alt=media" &&     unzip /tmp/chromedriver.zip -d /opt/ &&     unzip /tmp/chrome-linux.zip -d /opt/
 ---> Using cache
 ---> 187c7d849bef
Step 3/9 : FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55
 ---> ec11cea4dd41
Step 4/9 : RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib     libXcursor libXdamage libXext libXi libXrandr libXScrnSaver     libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb     xorg-x11-xauth dbus-glib dbus-glib-devel -y
 ---> Using cache
 ---> 7dfe8aea5ec1
Step 5/9 : RUN pip install selenium
 ---> Using cache
 ---> a98b23058aff
Step 6/9 : COPY --from=build /opt/chrome-linux /opt/chrome
 ---> Using cache
 ---> 42f7f809a529
Step 7/9 : COPY --from=build /opt/chromedriver /opt/
 ---> Using cache
 ---> d59b22d93d94
Step 8/9 : COPY test.py ./
 ---> Using cache
 ---> 8bd3b19e0e06
Step 9/9 : CMD [ "test.handler" ]
 ---> Using cache
 ---> 54928edad7ca
Successfully built 54928edad7ca
Successfully tagged serverless-docker-selenium-lambda-prod:img

Login to Docker succeeded!
Warning: Docker authentication token will be stored unencrypted in docker config. Configure Docker credential helper to remove this warning.

✖ Stack docker-selenium-lambda-prod failed to deploy (165s)
Environment: linux, node 16.15.0, framework 3.16.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Encountered error during executing: docker push,965921893518.dkr.ecr.eu-central-1.amazonaws.com/serverless-docker-selenium-lambda-prod:img
Output of the command:
The push refers to repository [965921893518.dkr.ecr.eu-central-1.amazonaws.com/serverless-docker-selenium-lambda-prod]
ed3dd29aba64: Preparing
35d5510de2d2: Preparing
2cdd43c88afc: Preparing
0847d0e8d776: Preparing
12f97f027ec8: Preparing
a8b55e94d2b2: Preparing
deb207ae2541: Preparing
5f96311c404e: Preparing
6a0bca2873ed: Preparing
435bd6980d66: Preparing
c0bc13e98dfd: Preparing
6a0bca2873ed: Waiting
deb207ae2541: Waiting
5f96311c404e: Waiting
435bd6980d66: Waiting
c0bc13e98dfd: Waiting
a8b55e94d2b2: Waiting
ed3dd29aba64: Retrying in 5 seconds
ed3dd29aba64: Retrying in 4 seconds
ed3dd29aba64: Retrying in 3 seconds
ed3dd29aba64: Retrying in 2 seconds
ed3dd29aba64: Retrying in 1 second
ed3dd29aba64: Retrying in 10 seconds
ed3dd29aba64: Retrying in 9 seconds
ed3dd29aba64: Retrying in 8 seconds
ed3dd29aba64: Retrying in 7 seconds
ed3dd29aba64: Retrying in 6 seconds
ed3dd29aba64: Retrying in 5 seconds
ed3dd29aba64: Retrying in 4 seconds
ed3dd29aba64: Retrying in 3 seconds
ed3dd29aba64: Retrying in 2 seconds
ed3dd29aba64: Retrying in 1 second
ed3dd29aba64: Retrying in 15 seconds
ed3dd29aba64: Retrying in 14 seconds
ed3dd29aba64: Retrying in 13 seconds
ed3dd29aba64: Retrying in 12 seconds
2cdd43c88afc: Retrying in 5 seconds
ed3dd29aba64: Retrying in 11 seconds
2cdd43c88afc: Retrying in 4 seconds
ed3dd29aba64: Retrying in 10 seconds
2cdd43c88afc: Retrying in 3 seconds
ed3dd29aba64: Retrying in 9 seconds
2cdd43c88afc: Retrying in 2 seconds
ed3dd29aba64: Retrying in 8 seconds
2cdd43c88afc: Retrying in 1 second
ed3dd29aba64: Retrying in 7 seconds
ed3dd29aba64: Retrying in 6 seconds
0847d0e8d776: Retrying in 5 seconds
ed3dd29aba64: Retrying in 5 seconds
35d5510de2d2: Retrying in 5 seconds
0847d0e8d776: Retrying in 4 seconds
ed3dd29aba64: Retrying in 4 seconds
35d5510de2d2: Retrying in 4 seconds
0847d0e8d776: Retrying in 3 seconds
ed3dd29aba64: Retrying in 3 seconds
12f97f027ec8: Retrying in 5 seconds
35d5510de2d2: Retrying in 3 seconds
0847d0e8d776: Retrying in 2 seconds
ed3dd29aba64: Retrying in 2 seconds
12f97f027ec8: Retrying in 4 seconds
35d5510de2d2: Retrying in 2 seconds
0847d0e8d776: Retrying in 1 second
ed3dd29aba64: Retrying in 1 second
12f97f027ec8: Retrying in 3 seconds
35d5510de2d2: Retrying in 1 second
12f97f027ec8: Retrying in 2 seconds
12f97f027ec8: Retrying in 1 second
12f97f027ec8: Retrying in 10 seconds
ed3dd29aba64: Retrying in 20 seconds
12f97f027ec8: Retrying in 9 seconds
ed3dd29aba64: Retrying in 19 seconds
12f97f027ec8: Retrying in 8 seconds
ed3dd29aba64: Retrying in 18 seconds
12f97f027ec8: Retrying in 7 seconds
ed3dd29aba64: Retrying in 17 seconds
12f97f027ec8: Retrying in 6 seconds
ed3dd29aba64: Retrying in 16 seconds
12f97f027ec8: Retrying in 5 seconds
ed3dd29aba64: Retrying in 15 seconds
12f97f027ec8: Retrying in 4 seconds
ed3dd29aba64: Retrying in 14 seconds
12f97f027ec8: Retrying in 3 seconds
ed3dd29aba64: Retrying in 13 seconds
12f97f027ec8: Retrying in 2 seconds
ed3dd29aba64: Retrying in 12 seconds
12f97f027ec8: Retrying in 1 second
ed3dd29aba64: Retrying in 11 seconds
ed3dd29aba64: Retrying in 10 seconds
ed3dd29aba64: Retrying in 9 seconds
ed3dd29aba64: Retrying in 8 seconds
ed3dd29aba64: Retrying in 7 seconds
ed3dd29aba64: Retrying in 6 seconds
ed3dd29aba64: Retrying in 5 seconds
ed3dd29aba64: Retrying in 4 seconds
ed3dd29aba64: Retrying in 3 seconds
ed3dd29aba64: Retrying in 2 seconds
ed3dd29aba64: Retrying in 1 second
12f97f027ec8: Retrying in 15 seconds
12f97f027ec8: Retrying in 14 seconds
12f97f027ec8: Retrying in 13 seconds
12f97f027ec8: Retrying in 12 seconds
12f97f027ec8: Retrying in 11 seconds
12f97f027ec8: Retrying in 10 seconds
12f97f027ec8: Retrying in 9 seconds
12f97f027ec8: Retrying in 8 seconds
12f97f027ec8: Retrying in 7 seconds
12f97f027ec8: Retrying in 6 seconds
12f97f027ec8: Retrying in 5 seconds
dial tcp 3.121.190.14:443: i/o timeout

**Comment by umihico** [comment]
Seems IAM permission issue? Can you use AdministratorAccess?

https://stackoverflow.com/questions/70828205/pushing-an-image-to-ecr-getting-retrying-in-seconds

**Comment by bklaus002** [comment]
> Seems IAM permission issue? Can you use AdministratorAccess?
> 
> https://stackoverflow.com/questions/70828205/pushing-an-image-to-ecr-getting-retrying-in-seconds

Many thanks for the link. I tried the following:
- I added the policy `AmazonEC2ContainerRegistryFullAccess` to the IAM user as in https://stackoverflow.com/questions/70452836/docker-push-to-aws-ecr-hangs-immediately-and-times-out/70453287#70453287
- I added the policy `AmazonEC2ContainerRegistryPowerUser` to the IAM user as in https://stackoverflow.com/questions/70828205/pushing-an-image-to-ecr-getting-retrying-in-seconds
- I added different permissions to the ECR as in https://stackoverflow.com/questions/70452836/docker-push-to-aws-ecr-hangs-immediately-and-times-out/70453287#70453287
- I changed the default region to `us-east-1` (as your YML-file mentions this region) as mentioned in https://www.youtube.com/watch?v=89ZeXaZEf80

None of those points solved the issue, I am still getting the same error.

**Comment by umihico** [comment]
Can you push any image into your ECR repository in general? If you can't, it is not this project problem.

I asked you to use AdministratorAccess. Serverless Framework requires lots of permissions..

**Comment by bklaus002** [comment]
> Can you push any image into your ECR repository in general? If you can't, it is not this project problem.
> 
> I asked you to use AdministratorAccess. Serverless Framework requires lots of permissions..

Actually, I have now tried to follow the steps in this link https://www.youtube.com/watch?v=89ZeXaZEf80 and I see that when starting the push command things appear to work.

ed3dd29aba64: Retrying in 1 second
35d5510de2d2: Retrying in 1 second
2cdd43c88afc: Pushing [====>                                              ]   38.4MB/454.8MB
0847d0e8d776: Pushing [===========================================>       ]  31.38MB/35.71MB
12f97f027ec8: Pushing [====>                                              ]  40.32MB/478.8MB
a8b55e94d2b2: Waiting
deb207ae2541: Waiting
5f96311c404e: Waiting
6a0bca2873ed: Waiting
435bd6980d66: Waiting
c0bc13e98dfd: Waiting
dial tcp 18.209.201.180:443: i/o timeout

To me it looks like the file sizes (the image appears to be 1.5GB) are just very large so it takes time. Can I increase the timeout limit somewhere?

And where in Serverless do I make this change to AdministratorAccess?

**Comment by bklaus002** [comment]
I followed the AWS push commands based on the steps shown in this video https://www.youtube.com/watch?v=89ZeXaZEf80 and used this small docker image https://github.com/alpinelinux/docker-alpine/tree/master as an example and it works for me. There is no timeout error there, the file sizes are a few MBs.

**Comment by umihico** [comment]
> And where in Serverless do I make this change to AdministratorAccess?

Serverless Framework use aws credentials by default

**Comment by umihico** [comment]
I'll reopen this issue again if this seems relate my repository problem

**Comment by bklaus002** [comment]
> > And where in Serverless do I make this change to AdministratorAccess?
> 
> Serverless Framework use aws credentials by default

I checked it and I had the AdministratorAccess rights already attached to my user. Unfortunately, while I am able to deploy a smaller repository, your 1.5GB image I am not able to deploy. To me it looks like there is a timeout error.

**Comment by bklaus002** [comment]
I just wanted to provide details on what the issue was and how I solved it for me. It turned out that, probably due to my internet connection speed and the docker default setting to try and upload five layers at a time, a timeout error occurred and deployment of the docker image was not successful. This issue is described also by other users, e.g. here: https://www.kovarus.com/blog/docker-push-timeout-to-aws-elastic-container-registry/.

It is possible to lower the number of layers that docker tries to upload at a time using the `dockerd` command, see the options here: https://docs.docker.com/engine/reference/commandline/dockerd/

At the end, `dockerd --max-concurrent-uploads 1` worked for me as it lowered the number of layers to one at a time and this prevented the timeout error from occurring.

The docker image was successfully installed and works. Many thanks to umihico!

**Comment by umihico** [comment]
wow I'm grad to hear that you solved. thank you for telling me about `--max-concurrent-uploads` option ;)
