### ISSUE TITLE
Upgrade chome version to 2.43

### ISSUE THREAD

**Issue by xoxwgys56** [umihico/docker-selenium-lambda#7]
Hey @umihico I must say this repository is so great. It is so helpful for me. 

But I have a question for about `Dockerfile`. You use chrome version 2.37. 
It looks like so old thing there is [release note](https://chromedriver.storage.googleapis.com/2.43/notes.txt) about this version. so I thought there is reason why you use this version. 

If not, I suggest higher version of chrome which [duolabmeng6](https://github.com/duolabmeng6) said in [this issue](https://github.com/adieuadieu/serverless-chrome/issues/133#issuecomment-853508521). I think version `86.0` takes more memory like *duolabmeng6* said so version `2.43` is more stable for lambda. 

---

### Additional attachment

only changed chrome version.

```dockerfile
FROM public.ecr.aws/lambda/python:3.8 as build
RUN yum install -y unzip && \
    curl -SL https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip > /tmp/chromedriver.zip && \
    curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-55/stable-headless-chromium-amazonlinux-2017-03.zip > /tmp/headless-chromium.zip && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/headless-chromium.zip -d /opt/

FROM public.ecr.aws/lambda/python:3.8
RUN yum install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
RUN pip install selenium
COPY --from=build /opt/headless-chromium /opt/
COPY --from=build /opt/chromedriver /opt/
COPY test.py ./
CMD [ "test.handler" ]
```

**Comment by umihico** [comment]
@xoxwgys56 
Thank you for your report. I also confirmed that `2.43` with `v1.0.0-55` works well. I don't have any specific reasons to keep using 2.37. It was just the latest version which I know works.

Could you give me a pull request? I'd like to add your name as a contributer.

**Comment by xoxwgys56** [comment]
@umihico Oh it is so pleasure to me become a contributor on your repository.  
Okay I make a pull request.

**Comment by xoxwgys56** [comment]
Created pull request
