### ISSUE TITLE
Spliting the Selenium - Chrome to a layer

### ISSUE THREAD

**Issue by boeschl** [umihico/docker-selenium-lambda#70]
First of all this is not actually an issue!! Thanks for posting this, I have been looking for an alternative for scrapping some sites, generating an API to use the website information and now is working !!
As an improvement, I tried to separate the elements and construct as a LAMBDA layer the elements of Selenium and Chrome, so is easier to deploy or even change the code of the scrapping (if the website changes something), but failed miserably.
The deployment only copies the files on the directory and nothing else any support will be greatly appreciated

Here is the content of the serverless.yml
service: docker-selenium-lambda

provider:
name: aws
stage: ${opt:stage, 'prod'}
region: ${env:AWS_REGION, 'us-east-2'}
ecr:
images:
img:
path: ./
platform: linux/amd64
layers:
selenium-lambda:
path: ./

And the Dockerfile
FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55 as build
RUN yum install -y unzip &&
curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip" &&
curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F982481%2Fchrome-linux.zip?alt=media" &&
unzip /tmp/chromedriver.zip -d /opt/ &&
unzip /tmp/chrome-linux.zip -d /opt/

FROM public.ecr.aws/lambda/python@sha256:2203844d7263f9c38a7f03f25bbb181772e93abc944de2b26ccca1689e1dde55
RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib
libXcursor libXdamage libXext libXi libXrandr libXScrnSaver
libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb
xorg-x11-xauth dbus-glib dbus-glib-devel -y
RUN pip install selenium
COPY --from=build /opt/chrome-linux /opt/chrome
COPY --from=build /opt/chromedriver /opt/

**Comment by umihico** [comment]
I think latest chromium with lambda layer will not work. As you see my Dockerfile install many dependencies by `yum`. This installation is required and I'm not sure Lambda layer can make it. Or you can use old customized chromium binary from https://github.com/adieuadieu/serverless-chrome

If you wanna have something common like lambda layer, you can just create base common docker image. Is this good enough for you?
