### ISSUE TITLE
Trying to load Extension

### ISSUE THREAD

**Issue by DiMiTriFrog** [umihico/docker-selenium-lambda#81]
I'm use this code for headless mode and work but I tried to do following this steps https://cloudbytes.dev/snippets/run-chrome-extensions-with-python-selenium-on-aws-lambda + the docker of this project and I have the Chrome is not reachable error..

**Comment by umihico** [comment]
I guess some version difference issue. For example, he is using `ubuntu:latest` but nobody know the difference between your today's version and his version on the day of the blog. That's why I test everything with binaries exactly versions specified.
