### ISSUE TITLE
XVFB Configuration for non-headless mode

### ISSUE THREAD

**Issue by lukehamil55** [umihico/docker-selenium-lambda#86]
Love this project, I have a _new feature_ request: 

How can this template be used to configure a XVFB display so that Selenium webdriver can run in non-headless mode? I have installed the XVFB wrapper in my docker file:
`RUN pip install xvfbwrapper`

When I run the following snippet, it works perfectly:
```
from xvfbwrapper import Xvfb

vdisplay = Xvfb()
vdisplay.start()
vdisplay.stop()
```

Running Selenium works as normal, however when I combine the two, I get the following error:
_[ERROR] SessionNotCreatedException: Message: session not created from disconnected: Unable to receive message from renderer (Session info: chrome=96.0.4664.0)_

More information can be found here: https://stackoverflow.com/questions/72650323/selenium-xvfb-unable-to-receive-message-from-renderer

**Comment by lukehamil55** [comment]
This will allow for running extensions in Selenium to run as originally inquired by [issue 81](https://github.com/umihico/docker-selenium-lambda/issues/81)

**Comment by umihico** [comment]
There are good conversations in #85 and I think it is okay to close this issue.
