### ISSUE TITLE
Port to AWS Lambda

### ISSUE THREAD

**Issue by fantasytc7** [umihico/docker-selenium-lambda#94]
Hi

Thank you for the great work
I want to write some code in AWS Lambda in python to leverage selenium, chrome-driver related library.
Hopefully, I can maintain my python code in lambda and use the image that you generated.
Would you please give me some hints to set this up ?

Many Thanks,
All the best!

Fanta

**Comment by umihico** [comment]
What do you want to do exatctly?

**Comment by fantasytc7** [comment]
Hi,

I want to run selenium/chromedriver on AWS Lambda

Thanks

**Comment by umihico** [comment]
You can archive it by following the example here, or could you show me where you get stuck if you already have tried?

https://github.com/umihico/docker-selenium-lambda#running-the-demo
